#!/usr/bin/env python3
"""Find Godot scripts/symbols or regenerate the repository's code map."""

import argparse
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MAP = ROOT / "docs/CODE-MAP.md"
LITERALS = re.compile(
    r'''\#[^\n]*|"""(?:\\.|(?!""")[\s\S])*"""|''' +
    r"'''(?:\\.|(?!''')[\s\S])*'''|" +
    r'''"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*' '''.rstrip(),
)
DECLARATION = re.compile(
    r"^(?P<kind>class_name|(?:static )?func|signal|const)\s+(?P<name>\w+)", re.MULTILINE
)


@dataclass
class Script:
    path: Path
    class_name: str
    lines: int
    symbols: list[tuple[int, str, str]]


def mask_literals(source):
    """Keep line positions while hiding comments and string contents."""
    return LITERALS.sub(lambda match: re.sub(r"[^\n]", " ", match.group()), source)


def index_project():
    scripts = []
    for path in sorted((ROOT / "project").rglob("*.gd")):
        if ".godot" in path.parts:
            continue
        source = path.read_text()
        symbols = []
        line, cursor = 1, 0
        for match in DECLARATION.finditer(mask_literals(source)):
            line += source.count("\n", cursor, match.start())
            cursor = match.start()
            symbols.append((line, match["kind"], match["name"]))
        class_name = next((name for _, kind, name in symbols if kind == "class_name"), "-")
        scripts.append(Script(path.relative_to(ROOT), class_name, len(source.splitlines()), symbols))
    return scripts


def render_map(scripts):
    groups = defaultdict(list)
    for script in scripts:
        groups[script.path.parent.as_posix()].append(script)
    lines = [
        "# Code map", "",
        "Generated by `python3 scripts/code_map.py --write`. Do not edit this file by hand.", "",
        "Start with [architecture and ownership](ARCHITECTURE.md) for responsibilities and change workflows.", "",
        "Find methods without opening a large file:", "",
        "```sh",
        "python3 scripts/code_map.py crime",
        "python3 scripts/code_map.py --symbols checkpoint restore",
        "python3 scripts/code_map.py --symbols MainScene _ready",
        "```", "",
        f"{len(scripts)} scripts; {sum(script.lines for script in scripts):,} source lines.", "",
        "## Largest files", "",
        "These remain refactoring candidates; line count is a navigation aid, not a quality rating.", "",
        "| Script | Lines | Functions |", "| --- | ---: | ---: |",
    ]
    for script in sorted(scripts, key=lambda item: (-item.lines, item.path.as_posix()))[:12]:
        count = sum(kind.endswith("func") for _, kind, _ in script.symbols)
        lines.append(f"| [{script.path.name}](../{script.path.as_posix()}) | {script.lines:,} | {count} |")
    for folder, entries in sorted(groups.items()):
        lines += ["", f"## {folder}", "", "| Script | Global class | Functions |", "| --- | --- | ---: |"]
        for script in entries:
            count = sum(kind.endswith("func") for _, kind, _ in script.symbols)
            lines.append(f"| [{script.path.name}](../{script.path.as_posix()}) | {script.class_name} | {count} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("query", nargs="*", help="Case-insensitive words; all must match the path or symbol")
    parser.add_argument("--symbols", action="store_true", help="Include top-level functions, signals and constants")
    parser.add_argument("--limit", type=int, default=40, help="Maximum results; 0 shows every match")
    output = parser.add_mutually_exclusive_group()
    output.add_argument("--write", action="store_true", help="Regenerate docs/CODE-MAP.md")
    output.add_argument("--check", action="store_true", help="Fail if the generated map is stale")
    args = parser.parse_args()
    if args.limit < 0:
        parser.error("--limit cannot be negative")
    scripts = index_project()
    if args.write or args.check:
        content = render_map(scripts)
        if args.write:
            MAP.write_text(content)
            print(f"Wrote {MAP.relative_to(ROOT)}")
            return 0
        if not MAP.exists() or MAP.read_text() != content:
            print("Code map is stale. Run: python3 scripts/code_map.py --write")
            return 1
        print("Code map is current.")
        return 0
    results = []
    for script in scripts:
        entries = script.symbols if args.symbols else [(1, "script", script.class_name)]
        for line, kind, name in entries:
            searchable = f"{script.path.as_posix()} {name}".casefold()
            if all(word.casefold() in searchable for word in args.query):
                exact = any(word.casefold() == name.casefold() for word in args.query)
                results.append((not exact, f"{script.path.as_posix()}:{line}: {kind} {name}"))
    results.sort(key=lambda row: row[0])
    results = [row[1] for row in results]
    print("\n".join(results[:args.limit] if args.limit else results))
    if args.limit and len(results) > args.limit:
        print(f"Showing {args.limit} of {len(results)} matches; narrow the query or use --limit 0.")
    return 0 if results else 1


if __name__ == "__main__":
    raise SystemExit(main())
